### ISSUE TITLE
Won't access server

### ISSUE THREAD

**Issue by KrunchMuffin** [wcomartin/PlexPy-Remote#20]
I have plexpy set up and its been working for months. Just saw remote and decided to install. When I add my URL and api key it says it can't connect. Are there logs I can look at? The URL works fine in browser.

**Comment by Wreave** [comment]
did you put the protocol and port in the url?
https://github.com/wcomartin/PlexPy-Remote/wiki/Connect-to-PlexPy-server

**Comment by KrunchMuffin** [comment]
Yes, we'll it's on 80, nginx does a rewrite to the main port.

**Comment by Wreave** [comment]
what connection message are you getting? do you see api access attempts in plexpy?

**Comment by KrunchMuffin** [comment]
I see this in the logs
PlexPy APIv2 :: API called with kwargs: {'cmd': u'get_activity', 'apikey': u'\xa0********e6'}
The actual error msg is ppy could not comm. with ur plex server. But url works fine

**Comment by Wreave** [comment]
Can you run this from your phone and replace API_KEY and the URLwith your information?
http://DOMAIN/api/v2?apikey=API_KEY&cmd=get_activity

**Comment by KrunchMuffin** [comment]
Figured it out. I went to grab the key from ur app and noticed it there was a space at the beginning. Removed it and it works. So maybe add trim function around it just in case. Thanks for the help.

**Comment by wcomartin** [comment]
Fixed this issue permanently
Thanks for bringing it to our attention.

https://github.com/wcomartin/PlexPy-Remote/commit/24fdb6274021f46bbb622b702d0b1130d134b5ab

**Comment by James-Glen-Work** [comment]
> I have plexpy set up and its been working for months. Just saw remote and decided to install. When I add my URL and api key it says it can't connect. Are there logs I can look at? The URL works fine in browser.

Hey, I was having the same issue. I had to open ports 80 and 8181 internally on Firewall, it connected straight away after that.
