### ISSUE TITLE
Android Error:  Error: Unexpected error, Javax.net.ssl.peerunverfiedexception:

### ISSUE THREAD

**Issue by seanvree** [wcomartin/PlexPy-Remote#30]
Mobile Device:  Galaxy S7 Android

PLEXPY VERSION 1.4.16 
Git Branch:	master
Git Commit Hash:	3742f33

Operating system: Windows 10E

Python Version:	2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]

Problem:
Trying to connect via PlexPY Remote Android App

What happened?

Error from PlexPY remote app:

Error: Unexpected error, Javax.net.ssl.peerunverfiedexception: Hostname: MYHOSTNAME
not verified cert: HASH

I can access the PlexPY webUI from a a HTTPs webfront.

What are your (relevant) settings:

Using PlexyPY with signed and valid certs

Trying to connect via PlexPY remote app on HTTPS://mydomainname:32500

Link to logs:

There is nothing in the logs when I try to connect via the app.

**Comment by wcomartin** [comment]
Use your plexpy URL not Plex url the port should be something like 8181 or nothing if your using a reverse proxy

**Comment by seanvree** [comment]
@wcomartin  - Ha, right. I got that. I am using my PlexPY port 32500.   Been using the app for 3 months, and then all of the sudden it stopped working.  

Again, I CAN access the WebUI via SSL.

**Comment by Wreave** [comment]
@seanvree are you using the HTTPS settings in PlexPy itself? If so are you using self signed certs or custom?

**Comment by seanvree** [comment]
@Wreave  - Yes, I'm using HTTPS in PlexPY, and it works fine from the WebUI.  I'm using let's encrypt.  

The certs are good.  Check for yourself:  Seanvree.com

**Comment by wcomartin** [comment]
@seanvree strange that i had to accept your certs in my browser before i could get to your page, i wonder if this has anything to do with that, but in the app I'm using a script to accept any certs provided. because there is no way for me to know if the cert is valid otherwise.

**Comment by JonnyWong16** [comment]
@seanvree Please, please, please, protect your website with proper security. We can can see your webcam, switch on your lights, and unlock your front door.

**Comment by seanvree** [comment]
@JonnyWong16  - Ha ha.  Yeah, I was just running some tests, so I disabled it temporarily.  Can you check now please?

**Comment by seanvree** [comment]
@wcomartin  - Yeah, I've noticed that too - I thought that was normal?  However, I don't think that's related, since I've always had to do that as well, and the app still worked.

**Comment by Wreave** [comment]
@seanvree Site looks protected now. So based on your cert and site map you are doing paths and not subdomains. My question is are you just using reverse proxy with letsencrypt or do you have specific certs set inside the plexpy settings?

**Comment by seanvree** [comment]
No reverse proxy right now (Although I'm trying to set it up but having issues with IIS).  The specific certs are directly mapped from the server into PlexPY.

**Comment by JonnyWong16** [comment]
Individual endpoints are still accessible:

yourdomain.com/sonarr
yourdomain.com/radarr
etc.

**Comment by seanvree** [comment]
@JonnyWong16  - I know. Reverse proxy is disabled at the moment.

**Comment by Wreave** [comment]
Are you able to access it locally using your server IP instead? Are there any conditions in which it works?

**Comment by seanvree** [comment]
@Wreave  - Didn't think to test that.  Yes, I can access it via SSL directly to my server via IP.  So looks like a problem with my certs?

**Comment by Wreave** [comment]
The cert itself looks okay, not sure where the issue is behind that. Can you try these tests?
https://github.com/wcomartin/PlexPy-Remote/wiki/api

**Comment by seanvree** [comment]
@Wreave worked:

https://seanvree.com:32500/api/v2?apikey=<REDACTED>&cmd=get_server_friendly_name

"response": {"message": null, "data": "VreePlexDesktop", "result": "success"}}

**Comment by Wreave** [comment]
@wcomartin any thoughts?

**Comment by seanvree** [comment]
@Wreave  - Okay, I removed the app, cleared the user data and reinstalled the app

It's working now.  

Weird. Right?
