### ISSUE TITLE
Can't connect to PlexPy

### ISSUE THREAD

**Issue by chrisvdgeld** [wcomartin/PlexPy-Remote#31]
Hi,

I can't seem to connect to PlexPy. 

**My host:**
https://sub.domain.com/plexpy

**API:**
The one generated in: Access Control - PlexPy

However, the PlexPy Remote app just keep on "searching" forever. Any reason why this could happen? (domain is with htaccess security, could this be a reason?)

**Comment by Wreave** [comment]
You need to make it so anything /api bypasses htaccess for that path.

**Comment by seanvree** [comment]
@Tailchakra  Yo buddy, not sure if you figured this out. I struggled with if for a few days, and I was stoked when I finally got it working.  Posted an comment on another question.  See here:

https://github.com/wcomartin/PlexPy-Remote/issues/34
