### ISSUE TITLE
Receive Notifications directly with PlexPy-Remote

### ISSUE THREAD

**Issue by nemchik** [wcomartin/PlexPy-Remote#35]
Since PlexPy has many options to send various Notifications, I think it would be great if PlexPy-Remote could be involved in the notification process in some way. I don't think it makes sense for PlexPy to try to push notifications to PlexPy-Remote as that probably requires a service to be provided in the cloud to handle that communication, but maybe the app could pull information from PlexPy as to when a notification would have otherwise been sent and then display a notification on my mobile device from PlexPy-Remote that might take me to a relevant section in the app?

**Comment by Wreave** [comment]
Stay tuned ;p
