### ISSUE TITLE
Git Hub version not showing

### ISSUE THREAD

**Issue by helsan74** [wcomartin/PlexPy-Remote#38]
For Plexpy remote I don't find my Git Hub version.

My PlexPy installation shows: Master instead of a version

How can I find my version?

Thanks

**Comment by Wreave** [comment]
Are you downloading the app from the Play Store?

**Comment by helsan74** [comment]
Yes PlexPy remote was downloaded from the Play store

**Comment by Wreave** [comment]
I am confused as to why you think there would be a git hub version displayed in the app? I don't believe there is anything to indicate that would be the case.

**Comment by Wreave** [comment]
If you are referring v2 for the QR scanner that is in reference to PlexPy v2 not the app. I would wait for the official release of v2.

**Comment by helsan74** [comment]
It just that im unable to PlexPy remote to work with my PlexPy.

So I was trying to understand how to add my Plexpy server to the app remote

**Comment by Wreave** [comment]
Have you tried following the faq?
https://github.com/wcomartin/PlexPy-Remote/wiki/Connect-to-PlexPy-server

**Comment by helsan74** [comment]
Yes this is where I saw the info for V2.

I always get Failed to authenticate with Plexy or Plex

**Comment by helsan74** [comment]
So I wanted to try with V2...but was not able to see my Git Branch

And then I opened this thread! :)

**Comment by JonnyWong16** [comment]
The QR scanner is broken on v2 so it won't help you anyways. You will still have to connect it manually by following the FAQ answer linked above.

**Comment by helsan74** [comment]
Found the problem!!

My PlexPy API key was not activated

PlexPyRemote working!

**Comment by helsan74** [comment]
Thanks for time and help!
