### ISSUE TITLE
Tautulli Remote does not support HTTP Auth - bug or by design?

### ISSUE THREAD

**Issue by mescon** [wcomartin/PlexPy-Remote#53]
I have all of my services behind a reverse proxy with HTTP Auth.

For example:
``https://user:password@example.com/tautulli``

In the Android Tautulli Remote, there is nowhere to enter user/pass for HTTP Auth which is fine. In some applications such as NZB360 I can just enter ``user:password@example.com`` as hostname and all is well.

In Tautulli Remote, it throws an error.

I don't want to call this a bug report or a feature request as I'm not sure if this is by design (because HTTP Auth isn't considered fully secure and is being deprecated over time), or if this is indeed a bug.

I'll let you decide.

Thanks a bunch for a great piece of software - I couldn't live without it!
Cheers!

**Comment by wcomartin** [comment]
It's not by design or a bug. More of an oversight.. it's in my list of things to implement but low because the apikey is auth enough. We've been telling people to just bypass the basic auth on /api until I get to implementing basic auth in the app

**Comment by mescon** [comment]
Ah, thanks for the feedback. Good idea!
Feel free to close the issue as your suggestion enables me to use Tautulli Remote just fine!

**Comment by tixetsal** [comment]
I would also love to see http auth support added to the app. Thank you for your work!

**Comment by sevospl** [comment]
Is there any particular reason to not support HTTP auth?
